name: web_parental_control
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: ^0.13.3
  flutter_launcher_icons: "^0.13.1"
  shared_preferences: ^2.2.0
  permission_handler: ^11.0.0
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.3+1
  mask_text_input_formatter: ^2.9.0
  intl: ^0.17.0
  image_picker: ^0.8.4+1
  file_picker: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoController.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logoController.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logoController.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logoController.png"



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Jura
      fonts:
        - asset: assets/fonts/Jura.ttf
